/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) diffusion_projection_unicycle_expl_vde_forw_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_project CASADI_PREFIX(project)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_trans CASADI_PREFIX(trans)
#define casadi_zeros CASADI_PREFIX(zeros)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

void casadi_project(const casadi_real* x, const casadi_int* sp_x, casadi_real* y, const casadi_int* sp_y, casadi_real* w) {
  casadi_int ncol_x, ncol_y, i, el;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  for (i=0; i<ncol_x; ++i) {
    for (el=colind_y[i]; el<colind_y[i+1]; ++el) w[row_y[el]] = 0;
    for (el=colind_x[i]; el<colind_x[i+1]; ++el) w[row_x[el]] = x[el];
    for (el=colind_y[i]; el<colind_y[i+1]; ++el) y[el] = w[row_y[el]];
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

static const casadi_int casadi_s0[7] = {5, 2, 0, 1, 2, 3, 4};
static const casadi_int casadi_s1[10] = 
  {2, 5, 0, 0, 0, 0, 1, 2,
  0, 1};
static const casadi_int casadi_s2[13] = 
  {5, 2, 0, 4, 8, 0, 1, 2,
  3, 0, 1, 2, 4};
static const casadi_int casadi_s3[11] = 
  {5, 2, 0, 3, 6, 0, 1, 2,
  0, 1, 2};
static const casadi_int casadi_s4[3] = {5, 1, 1};
static const casadi_int casadi_s5[3] = {5, 5, 1};
static const casadi_int casadi_s6[3] = {5, 2, 1};
static const casadi_int casadi_s7[3] = {2, 1, 1};
static const casadi_int casadi_s8[3] = {90, 1, 1};
static const casadi_int casadi_s9[23] = 
  {5, 5, 0, 3, 6, 9, 12, 15,
  0, 1, 2, 0, 1, 2, 0, 1,
  2, 0, 1, 2, 0, 1, 2};

static const casadi_real casadi_zeros[25] = 
  {0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0.};

/* diffusion_projection_unicycle_expl_vde_forw:(i0[5],i1[5x5],i2[5x2],i3[2],i4[90])->(o0[5],o1[5x5,15nz],o2[5x2,8nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real *rr, w00, w01, w02, w03, w10, w11, w12, w13, *w14=w+63, *w16=w+65, *w17=w+67;
  casadi_real *w18=w+69, *w20=w+87, *w21=w+90, *w22=w+93, *w23=w+99;
  const casadi_real *cs, *wr04, *wr05, *wr06, *wr07, *wr08, *wr09, *wr19;
  /* #0: @0 = input[0][3] */
  w00 = arg[0] ? arg[0][3] : 0;
  /* #1: @1 = input[0][2] */
  w01 = arg[0] ? arg[0][2] : 0;
  /* #2: @2 = cos(@1) */
  w02 = cos( w01 );
  /* #3: @3 = (@0*@2) */
  w03  = (w00*w02);
  /* #4: output[0][0] = @3 */
  if (res[0]) res[0][0] = w03;
  /* #5: @1 = sin(@1) */
  w01 = sin( w01 );
  /* #6: @3 = (@0*@1) */
  w03  = (w00*w01);
  /* #7: output[0][1] = @3 */
  if (res[0]) res[0][1] = w03;
  /* #8: @3 = input[0][4] */
  w03 = arg[0] ? arg[0][4] : 0;
  /* #9: output[0][2] = @3 */
  if (res[0]) res[0][2] = w03;
  /* #10: @3 = input[3][0] */
  w03 = arg[3] ? arg[3][0] : 0;
  /* #11: output[0][3] = @3 */
  if (res[0]) res[0][3] = w03;
  /* #12: @3 = input[3][1] */
  w03 = arg[3] ? arg[3][1] : 0;
  /* #13: output[0][4] = @3 */
  if (res[0]) res[0][4] = w03;
  /* #14: @4 = input[1][0] */
  wr04 = arg[1] ? arg[1] : casadi_zeros;
  /* #15: {@5, @6, @7, @8, @9} = horzsplit(@4) */
  wr05 = wr04;
  wr06 = wr04+5;
  wr07 = wr04+10;
  wr08 = wr04+15;
  wr09 = wr04+20;
  /* #16: {NULL, NULL, @3, @10, @11} = vertsplit(@5) */
  w03 = wr05[2];
  w10 = wr05[3];
  w11 = wr05[4];
  /* #17: @12 = (@2*@10) */
  w12  = (w02*w10);
  /* #18: @13 = (@1*@3) */
  w13  = (w01*w03);
  /* #19: @13 = (@0*@13) */
  w13  = (w00*w13);
  /* #20: @12 = (@12-@13) */
  w12 -= w13;
  /* #21: output[1][0] = @12 */
  if (res[1]) res[1][0] = w12;
  /* #22: @10 = (@1*@10) */
  w10  = (w01*w10);
  /* #23: @3 = (@2*@3) */
  w03  = (w02*w03);
  /* #24: @3 = (@0*@3) */
  w03  = (w00*w03);
  /* #25: @10 = (@10+@3) */
  w10 += w03;
  /* #26: output[1][1] = @10 */
  if (res[1]) res[1][1] = w10;
  /* #27: output[1][2] = @11 */
  if (res[1]) res[1][2] = w11;
  /* #28: {NULL, NULL, @11, @10, @3} = vertsplit(@6) */
  w11 = wr06[2];
  w10 = wr06[3];
  w03 = wr06[4];
  /* #29: @12 = (@2*@10) */
  w12  = (w02*w10);
  /* #30: @13 = (@1*@11) */
  w13  = (w01*w11);
  /* #31: @13 = (@0*@13) */
  w13  = (w00*w13);
  /* #32: @12 = (@12-@13) */
  w12 -= w13;
  /* #33: output[1][3] = @12 */
  if (res[1]) res[1][3] = w12;
  /* #34: @10 = (@1*@10) */
  w10  = (w01*w10);
  /* #35: @11 = (@2*@11) */
  w11  = (w02*w11);
  /* #36: @11 = (@0*@11) */
  w11  = (w00*w11);
  /* #37: @10 = (@10+@11) */
  w10 += w11;
  /* #38: output[1][4] = @10 */
  if (res[1]) res[1][4] = w10;
  /* #39: output[1][5] = @3 */
  if (res[1]) res[1][5] = w03;
  /* #40: {NULL, NULL, @3, @10, @11} = vertsplit(@7) */
  w03 = wr07[2];
  w10 = wr07[3];
  w11 = wr07[4];
  /* #41: @12 = (@2*@10) */
  w12  = (w02*w10);
  /* #42: @13 = (@1*@3) */
  w13  = (w01*w03);
  /* #43: @13 = (@0*@13) */
  w13  = (w00*w13);
  /* #44: @12 = (@12-@13) */
  w12 -= w13;
  /* #45: output[1][6] = @12 */
  if (res[1]) res[1][6] = w12;
  /* #46: @10 = (@1*@10) */
  w10  = (w01*w10);
  /* #47: @3 = (@2*@3) */
  w03  = (w02*w03);
  /* #48: @3 = (@0*@3) */
  w03  = (w00*w03);
  /* #49: @10 = (@10+@3) */
  w10 += w03;
  /* #50: output[1][7] = @10 */
  if (res[1]) res[1][7] = w10;
  /* #51: output[1][8] = @11 */
  if (res[1]) res[1][8] = w11;
  /* #52: {NULL, NULL, @11, @10, @3} = vertsplit(@8) */
  w11 = wr08[2];
  w10 = wr08[3];
  w03 = wr08[4];
  /* #53: @12 = (@2*@10) */
  w12  = (w02*w10);
  /* #54: @13 = (@1*@11) */
  w13  = (w01*w11);
  /* #55: @13 = (@0*@13) */
  w13  = (w00*w13);
  /* #56: @12 = (@12-@13) */
  w12 -= w13;
  /* #57: output[1][9] = @12 */
  if (res[1]) res[1][9] = w12;
  /* #58: @10 = (@1*@10) */
  w10  = (w01*w10);
  /* #59: @11 = (@2*@11) */
  w11  = (w02*w11);
  /* #60: @11 = (@0*@11) */
  w11  = (w00*w11);
  /* #61: @10 = (@10+@11) */
  w10 += w11;
  /* #62: output[1][10] = @10 */
  if (res[1]) res[1][10] = w10;
  /* #63: output[1][11] = @3 */
  if (res[1]) res[1][11] = w03;
  /* #64: {NULL, NULL, @3, @10, @11} = vertsplit(@9) */
  w03 = wr09[2];
  w10 = wr09[3];
  w11 = wr09[4];
  /* #65: @12 = (@2*@10) */
  w12  = (w02*w10);
  /* #66: @13 = (@1*@3) */
  w13  = (w01*w03);
  /* #67: @13 = (@0*@13) */
  w13  = (w00*w13);
  /* #68: @12 = (@12-@13) */
  w12 -= w13;
  /* #69: output[1][12] = @12 */
  if (res[1]) res[1][12] = w12;
  /* #70: @10 = (@1*@10) */
  w10  = (w01*w10);
  /* #71: @3 = (@2*@3) */
  w03  = (w02*w03);
  /* #72: @3 = (@0*@3) */
  w03  = (w00*w03);
  /* #73: @10 = (@10+@3) */
  w10 += w03;
  /* #74: output[1][13] = @10 */
  if (res[1]) res[1][13] = w10;
  /* #75: output[1][14] = @11 */
  if (res[1]) res[1][14] = w11;
  /* #76: @14 = zeros(2x5,2nz) */
  casadi_clear(w14, 2);
  /* #77: @15 = 00 */
  /* #78: @16 = ones(2x1) */
  casadi_fill(w16, 2, 1.);
  /* #79: {@11, @10} = vertsplit(@16) */
  w11 = w16[0];
  w10 = w16[1];
  /* #80: @16 = vertcat(@15, @15, @15, @11, @10) */
  rr=w16;
  *rr++ = w11;
  *rr++ = w10;
  /* #81: @17 = @16[:2] */
  for (rr=w17, cs=w16+0; cs!=w16+2; cs+=1) *rr++ = *cs;
  /* #82: (@14[:2] = @17) */
  for (rr=w14+0, cs=w17; rr!=w14+2; rr+=1) *rr = *cs++;
  /* #83: @17 = @14' */
  casadi_trans(w14,casadi_s1, w17, casadi_s0, iw);
  /* #84: @18 = project(@17) */
  casadi_project(w17, casadi_s0, w18, casadi_s2, w);
  /* #85: @19 = input[2][0] */
  wr19 = arg[2] ? arg[2] : casadi_zeros;
  /* #86: {@9, @8} = horzsplit(@19) */
  wr09 = wr19;
  wr08 = wr19+5;
  /* #87: {NULL, NULL, @11, @10, @3} = vertsplit(@9) */
  w11 = wr09[2];
  w10 = wr09[3];
  w03 = wr09[4];
  /* #88: @12 = (@2*@10) */
  w12  = (w02*w10);
  /* #89: @13 = (@1*@11) */
  w13  = (w01*w11);
  /* #90: @13 = (@0*@13) */
  w13  = (w00*w13);
  /* #91: @12 = (@12-@13) */
  w12 -= w13;
  /* #92: @10 = (@1*@10) */
  w10  = (w01*w10);
  /* #93: @11 = (@2*@11) */
  w11  = (w02*w11);
  /* #94: @11 = (@0*@11) */
  w11  = (w00*w11);
  /* #95: @10 = (@10+@11) */
  w10 += w11;
  /* #96: @20 = vertcat(@12, @10, @3, @15, @15) */
  rr=w20;
  *rr++ = w12;
  *rr++ = w10;
  *rr++ = w03;
  /* #97: {NULL, NULL, @12, @10, @3} = vertsplit(@8) */
  w12 = wr08[2];
  w10 = wr08[3];
  w03 = wr08[4];
  /* #98: @11 = (@2*@10) */
  w11  = (w02*w10);
  /* #99: @13 = (@1*@12) */
  w13  = (w01*w12);
  /* #100: @13 = (@0*@13) */
  w13  = (w00*w13);
  /* #101: @11 = (@11-@13) */
  w11 -= w13;
  /* #102: @1 = (@1*@10) */
  w01 *= w10;
  /* #103: @2 = (@2*@12) */
  w02 *= w12;
  /* #104: @0 = (@0*@2) */
  w00 *= w02;
  /* #105: @1 = (@1+@0) */
  w01 += w00;
  /* #106: @21 = vertcat(@11, @1, @3, @15, @15) */
  rr=w21;
  *rr++ = w11;
  *rr++ = w01;
  *rr++ = w03;
  /* #107: @22 = horzcat(@20, @21) */
  rr=w22;
  for (i=0, cs=w20; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w21; i<3; ++i) *rr++ = *cs++;
  /* #108: @23 = project(@22) */
  casadi_project(w22, casadi_s3, w23, casadi_s2, w);
  /* #109: @18 = (@18+@23) */
  for (i=0, rr=w18, cs=w23; i<8; ++i) (*rr++) += (*cs++);
  /* #110: output[2][0] = @18 */
  casadi_copy(w18, 8, res[2]);
  return 0;
}

CASADI_SYMBOL_EXPORT int diffusion_projection_unicycle_expl_vde_forw(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int diffusion_projection_unicycle_expl_vde_forw_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int diffusion_projection_unicycle_expl_vde_forw_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void diffusion_projection_unicycle_expl_vde_forw_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int diffusion_projection_unicycle_expl_vde_forw_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void diffusion_projection_unicycle_expl_vde_forw_release(int mem) {
}

CASADI_SYMBOL_EXPORT void diffusion_projection_unicycle_expl_vde_forw_incref(void) {
}

CASADI_SYMBOL_EXPORT void diffusion_projection_unicycle_expl_vde_forw_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int diffusion_projection_unicycle_expl_vde_forw_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int diffusion_projection_unicycle_expl_vde_forw_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real diffusion_projection_unicycle_expl_vde_forw_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* diffusion_projection_unicycle_expl_vde_forw_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* diffusion_projection_unicycle_expl_vde_forw_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* diffusion_projection_unicycle_expl_vde_forw_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s5;
    case 2: return casadi_s6;
    case 3: return casadi_s7;
    case 4: return casadi_s8;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* diffusion_projection_unicycle_expl_vde_forw_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s9;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int diffusion_projection_unicycle_expl_vde_forw_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 10;
  if (sz_res) *sz_res = 8;
  if (sz_iw) *sz_iw = 3;
  if (sz_w) *sz_w = 107;
  return 0;
}

CASADI_SYMBOL_EXPORT int diffusion_projection_unicycle_expl_vde_forw_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 10*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 8*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 3*sizeof(casadi_int);
  if (sz_w) *sz_w = 107*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
