/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) diffusion_projection_unicycle_constr_h_e_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {5, 1, 1};
static const casadi_int casadi_s1[3] = {0, 1, 1};
static const casadi_int casadi_s2[3] = {90, 1, 1};
static const casadi_int casadi_s3[3] = {30, 1, 1};

/* diffusion_projection_unicycle_constr_h_e_fun:(i0[5],i1[0],i2[0],i3[90])->(o0[30]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1, w2, w3;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = input[3][0] */
  w1 = arg[3] ? arg[3][0] : 0;
  /* #2: @1 = (@0-@1) */
  w1  = (w0-w1);
  /* #3: @1 = sq(@1) */
  w1 = casadi_sq( w1 );
  /* #4: @2 = input[0][1] */
  w2 = arg[0] ? arg[0][1] : 0;
  /* #5: @3 = input[3][1] */
  w3 = arg[3] ? arg[3][1] : 0;
  /* #6: @3 = (@2-@3) */
  w3  = (w2-w3);
  /* #7: @3 = sq(@3) */
  w3 = casadi_sq( w3 );
  /* #8: @1 = (@1+@3) */
  w1 += w3;
  /* #9: @3 = input[3][2] */
  w3 = arg[3] ? arg[3][2] : 0;
  /* #10: @3 = sq(@3) */
  w3 = casadi_sq( w3 );
  /* #11: @1 = (@1-@3) */
  w1 -= w3;
  /* #12: output[0][0] = @1 */
  if (res[0]) res[0][0] = w1;
  /* #13: @1 = input[3][3] */
  w1 = arg[3] ? arg[3][3] : 0;
  /* #14: @1 = (@0-@1) */
  w1  = (w0-w1);
  /* #15: @1 = sq(@1) */
  w1 = casadi_sq( w1 );
  /* #16: @3 = input[3][4] */
  w3 = arg[3] ? arg[3][4] : 0;
  /* #17: @3 = (@2-@3) */
  w3  = (w2-w3);
  /* #18: @3 = sq(@3) */
  w3 = casadi_sq( w3 );
  /* #19: @1 = (@1+@3) */
  w1 += w3;
  /* #20: @3 = input[3][5] */
  w3 = arg[3] ? arg[3][5] : 0;
  /* #21: @3 = sq(@3) */
  w3 = casadi_sq( w3 );
  /* #22: @1 = (@1-@3) */
  w1 -= w3;
  /* #23: output[0][1] = @1 */
  if (res[0]) res[0][1] = w1;
  /* #24: @1 = input[3][6] */
  w1 = arg[3] ? arg[3][6] : 0;
  /* #25: @1 = (@0-@1) */
  w1  = (w0-w1);
  /* #26: @1 = sq(@1) */
  w1 = casadi_sq( w1 );
  /* #27: @3 = input[3][7] */
  w3 = arg[3] ? arg[3][7] : 0;
  /* #28: @3 = (@2-@3) */
  w3  = (w2-w3);
  /* #29: @3 = sq(@3) */
  w3 = casadi_sq( w3 );
  /* #30: @1 = (@1+@3) */
  w1 += w3;
  /* #31: @3 = input[3][8] */
  w3 = arg[3] ? arg[3][8] : 0;
  /* #32: @3 = sq(@3) */
  w3 = casadi_sq( w3 );
  /* #33: @1 = (@1-@3) */
  w1 -= w3;
  /* #34: output[0][2] = @1 */
  if (res[0]) res[0][2] = w1;
  /* #35: @1 = input[3][9] */
  w1 = arg[3] ? arg[3][9] : 0;
  /* #36: @1 = (@0-@1) */
  w1  = (w0-w1);
  /* #37: @1 = sq(@1) */
  w1 = casadi_sq( w1 );
  /* #38: @3 = input[3][10] */
  w3 = arg[3] ? arg[3][10] : 0;
  /* #39: @3 = (@2-@3) */
  w3  = (w2-w3);
  /* #40: @3 = sq(@3) */
  w3 = casadi_sq( w3 );
  /* #41: @1 = (@1+@3) */
  w1 += w3;
  /* #42: @3 = input[3][11] */
  w3 = arg[3] ? arg[3][11] : 0;
  /* #43: @3 = sq(@3) */
  w3 = casadi_sq( w3 );
  /* #44: @1 = (@1-@3) */
  w1 -= w3;
  /* #45: output[0][3] = @1 */
  if (res[0]) res[0][3] = w1;
  /* #46: @1 = input[3][12] */
  w1 = arg[3] ? arg[3][12] : 0;
  /* #47: @1 = (@0-@1) */
  w1  = (w0-w1);
  /* #48: @1 = sq(@1) */
  w1 = casadi_sq( w1 );
  /* #49: @3 = input[3][13] */
  w3 = arg[3] ? arg[3][13] : 0;
  /* #50: @3 = (@2-@3) */
  w3  = (w2-w3);
  /* #51: @3 = sq(@3) */
  w3 = casadi_sq( w3 );
  /* #52: @1 = (@1+@3) */
  w1 += w3;
  /* #53: @3 = input[3][14] */
  w3 = arg[3] ? arg[3][14] : 0;
  /* #54: @3 = sq(@3) */
  w3 = casadi_sq( w3 );
  /* #55: @1 = (@1-@3) */
  w1 -= w3;
  /* #56: output[0][4] = @1 */
  if (res[0]) res[0][4] = w1;
  /* #57: @1 = input[3][15] */
  w1 = arg[3] ? arg[3][15] : 0;
  /* #58: @1 = (@0-@1) */
  w1  = (w0-w1);
  /* #59: @1 = sq(@1) */
  w1 = casadi_sq( w1 );
  /* #60: @3 = input[3][16] */
  w3 = arg[3] ? arg[3][16] : 0;
  /* #61: @3 = (@2-@3) */
  w3  = (w2-w3);
  /* #62: @3 = sq(@3) */
  w3 = casadi_sq( w3 );
  /* #63: @1 = (@1+@3) */
  w1 += w3;
  /* #64: @3 = input[3][17] */
  w3 = arg[3] ? arg[3][17] : 0;
  /* #65: @3 = sq(@3) */
  w3 = casadi_sq( w3 );
  /* #66: @1 = (@1-@3) */
  w1 -= w3;
  /* #67: output[0][5] = @1 */
  if (res[0]) res[0][5] = w1;
  /* #68: @1 = input[3][18] */
  w1 = arg[3] ? arg[3][18] : 0;
  /* #69: @1 = (@0-@1) */
  w1  = (w0-w1);
  /* #70: @1 = sq(@1) */
  w1 = casadi_sq( w1 );
  /* #71: @3 = input[3][19] */
  w3 = arg[3] ? arg[3][19] : 0;
  /* #72: @3 = (@2-@3) */
  w3  = (w2-w3);
  /* #73: @3 = sq(@3) */
  w3 = casadi_sq( w3 );
  /* #74: @1 = (@1+@3) */
  w1 += w3;
  /* #75: @3 = input[3][20] */
  w3 = arg[3] ? arg[3][20] : 0;
  /* #76: @3 = sq(@3) */
  w3 = casadi_sq( w3 );
  /* #77: @1 = (@1-@3) */
  w1 -= w3;
  /* #78: output[0][6] = @1 */
  if (res[0]) res[0][6] = w1;
  /* #79: @1 = input[3][21] */
  w1 = arg[3] ? arg[3][21] : 0;
  /* #80: @1 = (@0-@1) */
  w1  = (w0-w1);
  /* #81: @1 = sq(@1) */
  w1 = casadi_sq( w1 );
  /* #82: @3 = input[3][22] */
  w3 = arg[3] ? arg[3][22] : 0;
  /* #83: @3 = (@2-@3) */
  w3  = (w2-w3);
  /* #84: @3 = sq(@3) */
  w3 = casadi_sq( w3 );
  /* #85: @1 = (@1+@3) */
  w1 += w3;
  /* #86: @3 = input[3][23] */
  w3 = arg[3] ? arg[3][23] : 0;
  /* #87: @3 = sq(@3) */
  w3 = casadi_sq( w3 );
  /* #88: @1 = (@1-@3) */
  w1 -= w3;
  /* #89: output[0][7] = @1 */
  if (res[0]) res[0][7] = w1;
  /* #90: @1 = input[3][24] */
  w1 = arg[3] ? arg[3][24] : 0;
  /* #91: @1 = (@0-@1) */
  w1  = (w0-w1);
  /* #92: @1 = sq(@1) */
  w1 = casadi_sq( w1 );
  /* #93: @3 = input[3][25] */
  w3 = arg[3] ? arg[3][25] : 0;
  /* #94: @3 = (@2-@3) */
  w3  = (w2-w3);
  /* #95: @3 = sq(@3) */
  w3 = casadi_sq( w3 );
  /* #96: @1 = (@1+@3) */
  w1 += w3;
  /* #97: @3 = input[3][26] */
  w3 = arg[3] ? arg[3][26] : 0;
  /* #98: @3 = sq(@3) */
  w3 = casadi_sq( w3 );
  /* #99: @1 = (@1-@3) */
  w1 -= w3;
  /* #100: output[0][8] = @1 */
  if (res[0]) res[0][8] = w1;
  /* #101: @1 = input[3][27] */
  w1 = arg[3] ? arg[3][27] : 0;
  /* #102: @1 = (@0-@1) */
  w1  = (w0-w1);
  /* #103: @1 = sq(@1) */
  w1 = casadi_sq( w1 );
  /* #104: @3 = input[3][28] */
  w3 = arg[3] ? arg[3][28] : 0;
  /* #105: @3 = (@2-@3) */
  w3  = (w2-w3);
  /* #106: @3 = sq(@3) */
  w3 = casadi_sq( w3 );
  /* #107: @1 = (@1+@3) */
  w1 += w3;
  /* #108: @3 = input[3][29] */
  w3 = arg[3] ? arg[3][29] : 0;
  /* #109: @3 = sq(@3) */
  w3 = casadi_sq( w3 );
  /* #110: @1 = (@1-@3) */
  w1 -= w3;
  /* #111: output[0][9] = @1 */
  if (res[0]) res[0][9] = w1;
  /* #112: @1 = input[3][30] */
  w1 = arg[3] ? arg[3][30] : 0;
  /* #113: @1 = (@0-@1) */
  w1  = (w0-w1);
  /* #114: @1 = sq(@1) */
  w1 = casadi_sq( w1 );
  /* #115: @3 = input[3][31] */
  w3 = arg[3] ? arg[3][31] : 0;
  /* #116: @3 = (@2-@3) */
  w3  = (w2-w3);
  /* #117: @3 = sq(@3) */
  w3 = casadi_sq( w3 );
  /* #118: @1 = (@1+@3) */
  w1 += w3;
  /* #119: @3 = input[3][32] */
  w3 = arg[3] ? arg[3][32] : 0;
  /* #120: @3 = sq(@3) */
  w3 = casadi_sq( w3 );
  /* #121: @1 = (@1-@3) */
  w1 -= w3;
  /* #122: output[0][10] = @1 */
  if (res[0]) res[0][10] = w1;
  /* #123: @1 = input[3][33] */
  w1 = arg[3] ? arg[3][33] : 0;
  /* #124: @1 = (@0-@1) */
  w1  = (w0-w1);
  /* #125: @1 = sq(@1) */
  w1 = casadi_sq( w1 );
  /* #126: @3 = input[3][34] */
  w3 = arg[3] ? arg[3][34] : 0;
  /* #127: @3 = (@2-@3) */
  w3  = (w2-w3);
  /* #128: @3 = sq(@3) */
  w3 = casadi_sq( w3 );
  /* #129: @1 = (@1+@3) */
  w1 += w3;
  /* #130: @3 = input[3][35] */
  w3 = arg[3] ? arg[3][35] : 0;
  /* #131: @3 = sq(@3) */
  w3 = casadi_sq( w3 );
  /* #132: @1 = (@1-@3) */
  w1 -= w3;
  /* #133: output[0][11] = @1 */
  if (res[0]) res[0][11] = w1;
  /* #134: @1 = input[3][36] */
  w1 = arg[3] ? arg[3][36] : 0;
  /* #135: @1 = (@0-@1) */
  w1  = (w0-w1);
  /* #136: @1 = sq(@1) */
  w1 = casadi_sq( w1 );
  /* #137: @3 = input[3][37] */
  w3 = arg[3] ? arg[3][37] : 0;
  /* #138: @3 = (@2-@3) */
  w3  = (w2-w3);
  /* #139: @3 = sq(@3) */
  w3 = casadi_sq( w3 );
  /* #140: @1 = (@1+@3) */
  w1 += w3;
  /* #141: @3 = input[3][38] */
  w3 = arg[3] ? arg[3][38] : 0;
  /* #142: @3 = sq(@3) */
  w3 = casadi_sq( w3 );
  /* #143: @1 = (@1-@3) */
  w1 -= w3;
  /* #144: output[0][12] = @1 */
  if (res[0]) res[0][12] = w1;
  /* #145: @1 = input[3][39] */
  w1 = arg[3] ? arg[3][39] : 0;
  /* #146: @1 = (@0-@1) */
  w1  = (w0-w1);
  /* #147: @1 = sq(@1) */
  w1 = casadi_sq( w1 );
  /* #148: @3 = input[3][40] */
  w3 = arg[3] ? arg[3][40] : 0;
  /* #149: @3 = (@2-@3) */
  w3  = (w2-w3);
  /* #150: @3 = sq(@3) */
  w3 = casadi_sq( w3 );
  /* #151: @1 = (@1+@3) */
  w1 += w3;
  /* #152: @3 = input[3][41] */
  w3 = arg[3] ? arg[3][41] : 0;
  /* #153: @3 = sq(@3) */
  w3 = casadi_sq( w3 );
  /* #154: @1 = (@1-@3) */
  w1 -= w3;
  /* #155: output[0][13] = @1 */
  if (res[0]) res[0][13] = w1;
  /* #156: @1 = input[3][42] */
  w1 = arg[3] ? arg[3][42] : 0;
  /* #157: @1 = (@0-@1) */
  w1  = (w0-w1);
  /* #158: @1 = sq(@1) */
  w1 = casadi_sq( w1 );
  /* #159: @3 = input[3][43] */
  w3 = arg[3] ? arg[3][43] : 0;
  /* #160: @3 = (@2-@3) */
  w3  = (w2-w3);
  /* #161: @3 = sq(@3) */
  w3 = casadi_sq( w3 );
  /* #162: @1 = (@1+@3) */
  w1 += w3;
  /* #163: @3 = input[3][44] */
  w3 = arg[3] ? arg[3][44] : 0;
  /* #164: @3 = sq(@3) */
  w3 = casadi_sq( w3 );
  /* #165: @1 = (@1-@3) */
  w1 -= w3;
  /* #166: output[0][14] = @1 */
  if (res[0]) res[0][14] = w1;
  /* #167: @1 = input[3][45] */
  w1 = arg[3] ? arg[3][45] : 0;
  /* #168: @1 = (@0-@1) */
  w1  = (w0-w1);
  /* #169: @1 = sq(@1) */
  w1 = casadi_sq( w1 );
  /* #170: @3 = input[3][46] */
  w3 = arg[3] ? arg[3][46] : 0;
  /* #171: @3 = (@2-@3) */
  w3  = (w2-w3);
  /* #172: @3 = sq(@3) */
  w3 = casadi_sq( w3 );
  /* #173: @1 = (@1+@3) */
  w1 += w3;
  /* #174: @3 = input[3][47] */
  w3 = arg[3] ? arg[3][47] : 0;
  /* #175: @3 = sq(@3) */
  w3 = casadi_sq( w3 );
  /* #176: @1 = (@1-@3) */
  w1 -= w3;
  /* #177: output[0][15] = @1 */
  if (res[0]) res[0][15] = w1;
  /* #178: @1 = input[3][48] */
  w1 = arg[3] ? arg[3][48] : 0;
  /* #179: @1 = (@0-@1) */
  w1  = (w0-w1);
  /* #180: @1 = sq(@1) */
  w1 = casadi_sq( w1 );
  /* #181: @3 = input[3][49] */
  w3 = arg[3] ? arg[3][49] : 0;
  /* #182: @3 = (@2-@3) */
  w3  = (w2-w3);
  /* #183: @3 = sq(@3) */
  w3 = casadi_sq( w3 );
  /* #184: @1 = (@1+@3) */
  w1 += w3;
  /* #185: @3 = input[3][50] */
  w3 = arg[3] ? arg[3][50] : 0;
  /* #186: @3 = sq(@3) */
  w3 = casadi_sq( w3 );
  /* #187: @1 = (@1-@3) */
  w1 -= w3;
  /* #188: output[0][16] = @1 */
  if (res[0]) res[0][16] = w1;
  /* #189: @1 = input[3][51] */
  w1 = arg[3] ? arg[3][51] : 0;
  /* #190: @1 = (@0-@1) */
  w1  = (w0-w1);
  /* #191: @1 = sq(@1) */
  w1 = casadi_sq( w1 );
  /* #192: @3 = input[3][52] */
  w3 = arg[3] ? arg[3][52] : 0;
  /* #193: @3 = (@2-@3) */
  w3  = (w2-w3);
  /* #194: @3 = sq(@3) */
  w3 = casadi_sq( w3 );
  /* #195: @1 = (@1+@3) */
  w1 += w3;
  /* #196: @3 = input[3][53] */
  w3 = arg[3] ? arg[3][53] : 0;
  /* #197: @3 = sq(@3) */
  w3 = casadi_sq( w3 );
  /* #198: @1 = (@1-@3) */
  w1 -= w3;
  /* #199: output[0][17] = @1 */
  if (res[0]) res[0][17] = w1;
  /* #200: @1 = input[3][54] */
  w1 = arg[3] ? arg[3][54] : 0;
  /* #201: @1 = (@0-@1) */
  w1  = (w0-w1);
  /* #202: @1 = sq(@1) */
  w1 = casadi_sq( w1 );
  /* #203: @3 = input[3][55] */
  w3 = arg[3] ? arg[3][55] : 0;
  /* #204: @3 = (@2-@3) */
  w3  = (w2-w3);
  /* #205: @3 = sq(@3) */
  w3 = casadi_sq( w3 );
  /* #206: @1 = (@1+@3) */
  w1 += w3;
  /* #207: @3 = input[3][56] */
  w3 = arg[3] ? arg[3][56] : 0;
  /* #208: @3 = sq(@3) */
  w3 = casadi_sq( w3 );
  /* #209: @1 = (@1-@3) */
  w1 -= w3;
  /* #210: output[0][18] = @1 */
  if (res[0]) res[0][18] = w1;
  /* #211: @1 = input[3][57] */
  w1 = arg[3] ? arg[3][57] : 0;
  /* #212: @1 = (@0-@1) */
  w1  = (w0-w1);
  /* #213: @1 = sq(@1) */
  w1 = casadi_sq( w1 );
  /* #214: @3 = input[3][58] */
  w3 = arg[3] ? arg[3][58] : 0;
  /* #215: @3 = (@2-@3) */
  w3  = (w2-w3);
  /* #216: @3 = sq(@3) */
  w3 = casadi_sq( w3 );
  /* #217: @1 = (@1+@3) */
  w1 += w3;
  /* #218: @3 = input[3][59] */
  w3 = arg[3] ? arg[3][59] : 0;
  /* #219: @3 = sq(@3) */
  w3 = casadi_sq( w3 );
  /* #220: @1 = (@1-@3) */
  w1 -= w3;
  /* #221: output[0][19] = @1 */
  if (res[0]) res[0][19] = w1;
  /* #222: @1 = input[3][60] */
  w1 = arg[3] ? arg[3][60] : 0;
  /* #223: @1 = (@0-@1) */
  w1  = (w0-w1);
  /* #224: @1 = sq(@1) */
  w1 = casadi_sq( w1 );
  /* #225: @3 = input[3][61] */
  w3 = arg[3] ? arg[3][61] : 0;
  /* #226: @3 = (@2-@3) */
  w3  = (w2-w3);
  /* #227: @3 = sq(@3) */
  w3 = casadi_sq( w3 );
  /* #228: @1 = (@1+@3) */
  w1 += w3;
  /* #229: @3 = input[3][62] */
  w3 = arg[3] ? arg[3][62] : 0;
  /* #230: @3 = sq(@3) */
  w3 = casadi_sq( w3 );
  /* #231: @1 = (@1-@3) */
  w1 -= w3;
  /* #232: output[0][20] = @1 */
  if (res[0]) res[0][20] = w1;
  /* #233: @1 = input[3][63] */
  w1 = arg[3] ? arg[3][63] : 0;
  /* #234: @1 = (@0-@1) */
  w1  = (w0-w1);
  /* #235: @1 = sq(@1) */
  w1 = casadi_sq( w1 );
  /* #236: @3 = input[3][64] */
  w3 = arg[3] ? arg[3][64] : 0;
  /* #237: @3 = (@2-@3) */
  w3  = (w2-w3);
  /* #238: @3 = sq(@3) */
  w3 = casadi_sq( w3 );
  /* #239: @1 = (@1+@3) */
  w1 += w3;
  /* #240: @3 = input[3][65] */
  w3 = arg[3] ? arg[3][65] : 0;
  /* #241: @3 = sq(@3) */
  w3 = casadi_sq( w3 );
  /* #242: @1 = (@1-@3) */
  w1 -= w3;
  /* #243: output[0][21] = @1 */
  if (res[0]) res[0][21] = w1;
  /* #244: @1 = input[3][66] */
  w1 = arg[3] ? arg[3][66] : 0;
  /* #245: @1 = (@0-@1) */
  w1  = (w0-w1);
  /* #246: @1 = sq(@1) */
  w1 = casadi_sq( w1 );
  /* #247: @3 = input[3][67] */
  w3 = arg[3] ? arg[3][67] : 0;
  /* #248: @3 = (@2-@3) */
  w3  = (w2-w3);
  /* #249: @3 = sq(@3) */
  w3 = casadi_sq( w3 );
  /* #250: @1 = (@1+@3) */
  w1 += w3;
  /* #251: @3 = input[3][68] */
  w3 = arg[3] ? arg[3][68] : 0;
  /* #252: @3 = sq(@3) */
  w3 = casadi_sq( w3 );
  /* #253: @1 = (@1-@3) */
  w1 -= w3;
  /* #254: output[0][22] = @1 */
  if (res[0]) res[0][22] = w1;
  /* #255: @1 = input[3][69] */
  w1 = arg[3] ? arg[3][69] : 0;
  /* #256: @1 = (@0-@1) */
  w1  = (w0-w1);
  /* #257: @1 = sq(@1) */
  w1 = casadi_sq( w1 );
  /* #258: @3 = input[3][70] */
  w3 = arg[3] ? arg[3][70] : 0;
  /* #259: @3 = (@2-@3) */
  w3  = (w2-w3);
  /* #260: @3 = sq(@3) */
  w3 = casadi_sq( w3 );
  /* #261: @1 = (@1+@3) */
  w1 += w3;
  /* #262: @3 = input[3][71] */
  w3 = arg[3] ? arg[3][71] : 0;
  /* #263: @3 = sq(@3) */
  w3 = casadi_sq( w3 );
  /* #264: @1 = (@1-@3) */
  w1 -= w3;
  /* #265: output[0][23] = @1 */
  if (res[0]) res[0][23] = w1;
  /* #266: @1 = input[3][72] */
  w1 = arg[3] ? arg[3][72] : 0;
  /* #267: @1 = (@0-@1) */
  w1  = (w0-w1);
  /* #268: @1 = sq(@1) */
  w1 = casadi_sq( w1 );
  /* #269: @3 = input[3][73] */
  w3 = arg[3] ? arg[3][73] : 0;
  /* #270: @3 = (@2-@3) */
  w3  = (w2-w3);
  /* #271: @3 = sq(@3) */
  w3 = casadi_sq( w3 );
  /* #272: @1 = (@1+@3) */
  w1 += w3;
  /* #273: @3 = input[3][74] */
  w3 = arg[3] ? arg[3][74] : 0;
  /* #274: @3 = sq(@3) */
  w3 = casadi_sq( w3 );
  /* #275: @1 = (@1-@3) */
  w1 -= w3;
  /* #276: output[0][24] = @1 */
  if (res[0]) res[0][24] = w1;
  /* #277: @1 = input[3][75] */
  w1 = arg[3] ? arg[3][75] : 0;
  /* #278: @1 = (@0-@1) */
  w1  = (w0-w1);
  /* #279: @1 = sq(@1) */
  w1 = casadi_sq( w1 );
  /* #280: @3 = input[3][76] */
  w3 = arg[3] ? arg[3][76] : 0;
  /* #281: @3 = (@2-@3) */
  w3  = (w2-w3);
  /* #282: @3 = sq(@3) */
  w3 = casadi_sq( w3 );
  /* #283: @1 = (@1+@3) */
  w1 += w3;
  /* #284: @3 = input[3][77] */
  w3 = arg[3] ? arg[3][77] : 0;
  /* #285: @3 = sq(@3) */
  w3 = casadi_sq( w3 );
  /* #286: @1 = (@1-@3) */
  w1 -= w3;
  /* #287: output[0][25] = @1 */
  if (res[0]) res[0][25] = w1;
  /* #288: @1 = input[3][78] */
  w1 = arg[3] ? arg[3][78] : 0;
  /* #289: @1 = (@0-@1) */
  w1  = (w0-w1);
  /* #290: @1 = sq(@1) */
  w1 = casadi_sq( w1 );
  /* #291: @3 = input[3][79] */
  w3 = arg[3] ? arg[3][79] : 0;
  /* #292: @3 = (@2-@3) */
  w3  = (w2-w3);
  /* #293: @3 = sq(@3) */
  w3 = casadi_sq( w3 );
  /* #294: @1 = (@1+@3) */
  w1 += w3;
  /* #295: @3 = input[3][80] */
  w3 = arg[3] ? arg[3][80] : 0;
  /* #296: @3 = sq(@3) */
  w3 = casadi_sq( w3 );
  /* #297: @1 = (@1-@3) */
  w1 -= w3;
  /* #298: output[0][26] = @1 */
  if (res[0]) res[0][26] = w1;
  /* #299: @1 = input[3][81] */
  w1 = arg[3] ? arg[3][81] : 0;
  /* #300: @1 = (@0-@1) */
  w1  = (w0-w1);
  /* #301: @1 = sq(@1) */
  w1 = casadi_sq( w1 );
  /* #302: @3 = input[3][82] */
  w3 = arg[3] ? arg[3][82] : 0;
  /* #303: @3 = (@2-@3) */
  w3  = (w2-w3);
  /* #304: @3 = sq(@3) */
  w3 = casadi_sq( w3 );
  /* #305: @1 = (@1+@3) */
  w1 += w3;
  /* #306: @3 = input[3][83] */
  w3 = arg[3] ? arg[3][83] : 0;
  /* #307: @3 = sq(@3) */
  w3 = casadi_sq( w3 );
  /* #308: @1 = (@1-@3) */
  w1 -= w3;
  /* #309: output[0][27] = @1 */
  if (res[0]) res[0][27] = w1;
  /* #310: @1 = input[3][84] */
  w1 = arg[3] ? arg[3][84] : 0;
  /* #311: @1 = (@0-@1) */
  w1  = (w0-w1);
  /* #312: @1 = sq(@1) */
  w1 = casadi_sq( w1 );
  /* #313: @3 = input[3][85] */
  w3 = arg[3] ? arg[3][85] : 0;
  /* #314: @3 = (@2-@3) */
  w3  = (w2-w3);
  /* #315: @3 = sq(@3) */
  w3 = casadi_sq( w3 );
  /* #316: @1 = (@1+@3) */
  w1 += w3;
  /* #317: @3 = input[3][86] */
  w3 = arg[3] ? arg[3][86] : 0;
  /* #318: @3 = sq(@3) */
  w3 = casadi_sq( w3 );
  /* #319: @1 = (@1-@3) */
  w1 -= w3;
  /* #320: output[0][28] = @1 */
  if (res[0]) res[0][28] = w1;
  /* #321: @1 = input[3][87] */
  w1 = arg[3] ? arg[3][87] : 0;
  /* #322: @0 = (@0-@1) */
  w0 -= w1;
  /* #323: @0 = sq(@0) */
  w0 = casadi_sq( w0 );
  /* #324: @1 = input[3][88] */
  w1 = arg[3] ? arg[3][88] : 0;
  /* #325: @2 = (@2-@1) */
  w2 -= w1;
  /* #326: @2 = sq(@2) */
  w2 = casadi_sq( w2 );
  /* #327: @0 = (@0+@2) */
  w0 += w2;
  /* #328: @2 = input[3][89] */
  w2 = arg[3] ? arg[3][89] : 0;
  /* #329: @2 = sq(@2) */
  w2 = casadi_sq( w2 );
  /* #330: @0 = (@0-@2) */
  w0 -= w2;
  /* #331: output[0][29] = @0 */
  if (res[0]) res[0][29] = w0;
  return 0;
}

CASADI_SYMBOL_EXPORT int diffusion_projection_unicycle_constr_h_e_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int diffusion_projection_unicycle_constr_h_e_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int diffusion_projection_unicycle_constr_h_e_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void diffusion_projection_unicycle_constr_h_e_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int diffusion_projection_unicycle_constr_h_e_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void diffusion_projection_unicycle_constr_h_e_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void diffusion_projection_unicycle_constr_h_e_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void diffusion_projection_unicycle_constr_h_e_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int diffusion_projection_unicycle_constr_h_e_fun_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int diffusion_projection_unicycle_constr_h_e_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real diffusion_projection_unicycle_constr_h_e_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* diffusion_projection_unicycle_constr_h_e_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* diffusion_projection_unicycle_constr_h_e_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* diffusion_projection_unicycle_constr_h_e_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* diffusion_projection_unicycle_constr_h_e_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int diffusion_projection_unicycle_constr_h_e_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 4;
  return 0;
}

CASADI_SYMBOL_EXPORT int diffusion_projection_unicycle_constr_h_e_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 4*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
