/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) diffusion_projection_unicycle_constr_h_e_fun_jac_uxt_zt_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

static const casadi_int casadi_s0[3] = {5, 1, 1};
static const casadi_int casadi_s1[3] = {0, 1, 1};
static const casadi_int casadi_s2[3] = {90, 1, 1};
static const casadi_int casadi_s3[3] = {30, 1, 1};
static const casadi_int casadi_s4[93] = 
  {5, 30, 0, 2, 4, 6, 8, 10,
  12, 14, 16, 18, 20, 22, 24, 26,
  28, 30, 32, 34, 36, 38, 40, 42,
  44, 46, 48, 50, 52, 54, 56, 58,
  60, 0, 1, 0, 1, 0, 1, 0,
  1, 0, 1, 0, 1, 0, 1, 0,
  1, 0, 1, 0, 1, 0, 1, 0,
  1, 0, 1, 0, 1, 0, 1, 0,
  1, 0, 1, 0, 1, 0, 1, 0,
  1, 0, 1, 0, 1, 0, 1, 0,
  1, 0, 1, 0, 1, 0, 1, 0,
  1, 0, 1, 0, 1};
static const casadi_int casadi_s5[3] = {30, 0, 1};

/* diffusion_projection_unicycle_constr_h_e_fun_jac_uxt_zt:(i0[5],i1[0],i2[0],i3[90])->(o0[30],o1[5x30,60nz],o2[30x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real *rr, w00, w01, w02, w03, w04, w05, w06, w07, w08, w09, w10;
  casadi_real w11, w12, w13, w14, w15, w16, w17, w18, w19, w20, w21, w22;
  casadi_real w23, w24, w25, w26, w27, w28, w29, w30, w31, w32, w33, w34;
  casadi_real w35, w36, w37, w38, w39, w40, w41, w42, w43, w44, w45, w46;
  casadi_real w47, w48, w49, w50, w51, w52, w53, w54, w55, w56, w57, w58;
  casadi_real w59, w60, w61, *w62=w+62, *w63=w+122, *w64=w+126;
  const casadi_real *cs;
  /* #0: @0 = input[0][0] */
  w00 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = input[3][0] */
  w01 = arg[3] ? arg[3][0] : 0;
  /* #2: @1 = (@0-@1) */
  w01  = (w00-w01);
  /* #3: @2 = sq(@1) */
  w02 = casadi_sq( w01 );
  /* #4: @3 = input[0][1] */
  w03 = arg[0] ? arg[0][1] : 0;
  /* #5: @4 = input[3][1] */
  w04 = arg[3] ? arg[3][1] : 0;
  /* #6: @4 = (@3-@4) */
  w04  = (w03-w04);
  /* #7: @5 = sq(@4) */
  w05 = casadi_sq( w04 );
  /* #8: @2 = (@2+@5) */
  w02 += w05;
  /* #9: @5 = input[3][2] */
  w05 = arg[3] ? arg[3][2] : 0;
  /* #10: @5 = sq(@5) */
  w05 = casadi_sq( w05 );
  /* #11: @2 = (@2-@5) */
  w02 -= w05;
  /* #12: output[0][0] = @2 */
  if (res[0]) res[0][0] = w02;
  /* #13: @2 = input[3][3] */
  w02 = arg[3] ? arg[3][3] : 0;
  /* #14: @2 = (@0-@2) */
  w02  = (w00-w02);
  /* #15: @5 = sq(@2) */
  w05 = casadi_sq( w02 );
  /* #16: @6 = input[3][4] */
  w06 = arg[3] ? arg[3][4] : 0;
  /* #17: @6 = (@3-@6) */
  w06  = (w03-w06);
  /* #18: @7 = sq(@6) */
  w07 = casadi_sq( w06 );
  /* #19: @5 = (@5+@7) */
  w05 += w07;
  /* #20: @7 = input[3][5] */
  w07 = arg[3] ? arg[3][5] : 0;
  /* #21: @7 = sq(@7) */
  w07 = casadi_sq( w07 );
  /* #22: @5 = (@5-@7) */
  w05 -= w07;
  /* #23: output[0][1] = @5 */
  if (res[0]) res[0][1] = w05;
  /* #24: @5 = input[3][6] */
  w05 = arg[3] ? arg[3][6] : 0;
  /* #25: @5 = (@0-@5) */
  w05  = (w00-w05);
  /* #26: @7 = sq(@5) */
  w07 = casadi_sq( w05 );
  /* #27: @8 = input[3][7] */
  w08 = arg[3] ? arg[3][7] : 0;
  /* #28: @8 = (@3-@8) */
  w08  = (w03-w08);
  /* #29: @9 = sq(@8) */
  w09 = casadi_sq( w08 );
  /* #30: @7 = (@7+@9) */
  w07 += w09;
  /* #31: @9 = input[3][8] */
  w09 = arg[3] ? arg[3][8] : 0;
  /* #32: @9 = sq(@9) */
  w09 = casadi_sq( w09 );
  /* #33: @7 = (@7-@9) */
  w07 -= w09;
  /* #34: output[0][2] = @7 */
  if (res[0]) res[0][2] = w07;
  /* #35: @7 = input[3][9] */
  w07 = arg[3] ? arg[3][9] : 0;
  /* #36: @7 = (@0-@7) */
  w07  = (w00-w07);
  /* #37: @9 = sq(@7) */
  w09 = casadi_sq( w07 );
  /* #38: @10 = input[3][10] */
  w10 = arg[3] ? arg[3][10] : 0;
  /* #39: @10 = (@3-@10) */
  w10  = (w03-w10);
  /* #40: @11 = sq(@10) */
  w11 = casadi_sq( w10 );
  /* #41: @9 = (@9+@11) */
  w09 += w11;
  /* #42: @11 = input[3][11] */
  w11 = arg[3] ? arg[3][11] : 0;
  /* #43: @11 = sq(@11) */
  w11 = casadi_sq( w11 );
  /* #44: @9 = (@9-@11) */
  w09 -= w11;
  /* #45: output[0][3] = @9 */
  if (res[0]) res[0][3] = w09;
  /* #46: @9 = input[3][12] */
  w09 = arg[3] ? arg[3][12] : 0;
  /* #47: @9 = (@0-@9) */
  w09  = (w00-w09);
  /* #48: @11 = sq(@9) */
  w11 = casadi_sq( w09 );
  /* #49: @12 = input[3][13] */
  w12 = arg[3] ? arg[3][13] : 0;
  /* #50: @12 = (@3-@12) */
  w12  = (w03-w12);
  /* #51: @13 = sq(@12) */
  w13 = casadi_sq( w12 );
  /* #52: @11 = (@11+@13) */
  w11 += w13;
  /* #53: @13 = input[3][14] */
  w13 = arg[3] ? arg[3][14] : 0;
  /* #54: @13 = sq(@13) */
  w13 = casadi_sq( w13 );
  /* #55: @11 = (@11-@13) */
  w11 -= w13;
  /* #56: output[0][4] = @11 */
  if (res[0]) res[0][4] = w11;
  /* #57: @11 = input[3][15] */
  w11 = arg[3] ? arg[3][15] : 0;
  /* #58: @11 = (@0-@11) */
  w11  = (w00-w11);
  /* #59: @13 = sq(@11) */
  w13 = casadi_sq( w11 );
  /* #60: @14 = input[3][16] */
  w14 = arg[3] ? arg[3][16] : 0;
  /* #61: @14 = (@3-@14) */
  w14  = (w03-w14);
  /* #62: @15 = sq(@14) */
  w15 = casadi_sq( w14 );
  /* #63: @13 = (@13+@15) */
  w13 += w15;
  /* #64: @15 = input[3][17] */
  w15 = arg[3] ? arg[3][17] : 0;
  /* #65: @15 = sq(@15) */
  w15 = casadi_sq( w15 );
  /* #66: @13 = (@13-@15) */
  w13 -= w15;
  /* #67: output[0][5] = @13 */
  if (res[0]) res[0][5] = w13;
  /* #68: @13 = input[3][18] */
  w13 = arg[3] ? arg[3][18] : 0;
  /* #69: @13 = (@0-@13) */
  w13  = (w00-w13);
  /* #70: @15 = sq(@13) */
  w15 = casadi_sq( w13 );
  /* #71: @16 = input[3][19] */
  w16 = arg[3] ? arg[3][19] : 0;
  /* #72: @16 = (@3-@16) */
  w16  = (w03-w16);
  /* #73: @17 = sq(@16) */
  w17 = casadi_sq( w16 );
  /* #74: @15 = (@15+@17) */
  w15 += w17;
  /* #75: @17 = input[3][20] */
  w17 = arg[3] ? arg[3][20] : 0;
  /* #76: @17 = sq(@17) */
  w17 = casadi_sq( w17 );
  /* #77: @15 = (@15-@17) */
  w15 -= w17;
  /* #78: output[0][6] = @15 */
  if (res[0]) res[0][6] = w15;
  /* #79: @15 = input[3][21] */
  w15 = arg[3] ? arg[3][21] : 0;
  /* #80: @15 = (@0-@15) */
  w15  = (w00-w15);
  /* #81: @17 = sq(@15) */
  w17 = casadi_sq( w15 );
  /* #82: @18 = input[3][22] */
  w18 = arg[3] ? arg[3][22] : 0;
  /* #83: @18 = (@3-@18) */
  w18  = (w03-w18);
  /* #84: @19 = sq(@18) */
  w19 = casadi_sq( w18 );
  /* #85: @17 = (@17+@19) */
  w17 += w19;
  /* #86: @19 = input[3][23] */
  w19 = arg[3] ? arg[3][23] : 0;
  /* #87: @19 = sq(@19) */
  w19 = casadi_sq( w19 );
  /* #88: @17 = (@17-@19) */
  w17 -= w19;
  /* #89: output[0][7] = @17 */
  if (res[0]) res[0][7] = w17;
  /* #90: @17 = input[3][24] */
  w17 = arg[3] ? arg[3][24] : 0;
  /* #91: @17 = (@0-@17) */
  w17  = (w00-w17);
  /* #92: @19 = sq(@17) */
  w19 = casadi_sq( w17 );
  /* #93: @20 = input[3][25] */
  w20 = arg[3] ? arg[3][25] : 0;
  /* #94: @20 = (@3-@20) */
  w20  = (w03-w20);
  /* #95: @21 = sq(@20) */
  w21 = casadi_sq( w20 );
  /* #96: @19 = (@19+@21) */
  w19 += w21;
  /* #97: @21 = input[3][26] */
  w21 = arg[3] ? arg[3][26] : 0;
  /* #98: @21 = sq(@21) */
  w21 = casadi_sq( w21 );
  /* #99: @19 = (@19-@21) */
  w19 -= w21;
  /* #100: output[0][8] = @19 */
  if (res[0]) res[0][8] = w19;
  /* #101: @19 = input[3][27] */
  w19 = arg[3] ? arg[3][27] : 0;
  /* #102: @19 = (@0-@19) */
  w19  = (w00-w19);
  /* #103: @21 = sq(@19) */
  w21 = casadi_sq( w19 );
  /* #104: @22 = input[3][28] */
  w22 = arg[3] ? arg[3][28] : 0;
  /* #105: @22 = (@3-@22) */
  w22  = (w03-w22);
  /* #106: @23 = sq(@22) */
  w23 = casadi_sq( w22 );
  /* #107: @21 = (@21+@23) */
  w21 += w23;
  /* #108: @23 = input[3][29] */
  w23 = arg[3] ? arg[3][29] : 0;
  /* #109: @23 = sq(@23) */
  w23 = casadi_sq( w23 );
  /* #110: @21 = (@21-@23) */
  w21 -= w23;
  /* #111: output[0][9] = @21 */
  if (res[0]) res[0][9] = w21;
  /* #112: @21 = input[3][30] */
  w21 = arg[3] ? arg[3][30] : 0;
  /* #113: @21 = (@0-@21) */
  w21  = (w00-w21);
  /* #114: @23 = sq(@21) */
  w23 = casadi_sq( w21 );
  /* #115: @24 = input[3][31] */
  w24 = arg[3] ? arg[3][31] : 0;
  /* #116: @24 = (@3-@24) */
  w24  = (w03-w24);
  /* #117: @25 = sq(@24) */
  w25 = casadi_sq( w24 );
  /* #118: @23 = (@23+@25) */
  w23 += w25;
  /* #119: @25 = input[3][32] */
  w25 = arg[3] ? arg[3][32] : 0;
  /* #120: @25 = sq(@25) */
  w25 = casadi_sq( w25 );
  /* #121: @23 = (@23-@25) */
  w23 -= w25;
  /* #122: output[0][10] = @23 */
  if (res[0]) res[0][10] = w23;
  /* #123: @23 = input[3][33] */
  w23 = arg[3] ? arg[3][33] : 0;
  /* #124: @23 = (@0-@23) */
  w23  = (w00-w23);
  /* #125: @25 = sq(@23) */
  w25 = casadi_sq( w23 );
  /* #126: @26 = input[3][34] */
  w26 = arg[3] ? arg[3][34] : 0;
  /* #127: @26 = (@3-@26) */
  w26  = (w03-w26);
  /* #128: @27 = sq(@26) */
  w27 = casadi_sq( w26 );
  /* #129: @25 = (@25+@27) */
  w25 += w27;
  /* #130: @27 = input[3][35] */
  w27 = arg[3] ? arg[3][35] : 0;
  /* #131: @27 = sq(@27) */
  w27 = casadi_sq( w27 );
  /* #132: @25 = (@25-@27) */
  w25 -= w27;
  /* #133: output[0][11] = @25 */
  if (res[0]) res[0][11] = w25;
  /* #134: @25 = input[3][36] */
  w25 = arg[3] ? arg[3][36] : 0;
  /* #135: @25 = (@0-@25) */
  w25  = (w00-w25);
  /* #136: @27 = sq(@25) */
  w27 = casadi_sq( w25 );
  /* #137: @28 = input[3][37] */
  w28 = arg[3] ? arg[3][37] : 0;
  /* #138: @28 = (@3-@28) */
  w28  = (w03-w28);
  /* #139: @29 = sq(@28) */
  w29 = casadi_sq( w28 );
  /* #140: @27 = (@27+@29) */
  w27 += w29;
  /* #141: @29 = input[3][38] */
  w29 = arg[3] ? arg[3][38] : 0;
  /* #142: @29 = sq(@29) */
  w29 = casadi_sq( w29 );
  /* #143: @27 = (@27-@29) */
  w27 -= w29;
  /* #144: output[0][12] = @27 */
  if (res[0]) res[0][12] = w27;
  /* #145: @27 = input[3][39] */
  w27 = arg[3] ? arg[3][39] : 0;
  /* #146: @27 = (@0-@27) */
  w27  = (w00-w27);
  /* #147: @29 = sq(@27) */
  w29 = casadi_sq( w27 );
  /* #148: @30 = input[3][40] */
  w30 = arg[3] ? arg[3][40] : 0;
  /* #149: @30 = (@3-@30) */
  w30  = (w03-w30);
  /* #150: @31 = sq(@30) */
  w31 = casadi_sq( w30 );
  /* #151: @29 = (@29+@31) */
  w29 += w31;
  /* #152: @31 = input[3][41] */
  w31 = arg[3] ? arg[3][41] : 0;
  /* #153: @31 = sq(@31) */
  w31 = casadi_sq( w31 );
  /* #154: @29 = (@29-@31) */
  w29 -= w31;
  /* #155: output[0][13] = @29 */
  if (res[0]) res[0][13] = w29;
  /* #156: @29 = input[3][42] */
  w29 = arg[3] ? arg[3][42] : 0;
  /* #157: @29 = (@0-@29) */
  w29  = (w00-w29);
  /* #158: @31 = sq(@29) */
  w31 = casadi_sq( w29 );
  /* #159: @32 = input[3][43] */
  w32 = arg[3] ? arg[3][43] : 0;
  /* #160: @32 = (@3-@32) */
  w32  = (w03-w32);
  /* #161: @33 = sq(@32) */
  w33 = casadi_sq( w32 );
  /* #162: @31 = (@31+@33) */
  w31 += w33;
  /* #163: @33 = input[3][44] */
  w33 = arg[3] ? arg[3][44] : 0;
  /* #164: @33 = sq(@33) */
  w33 = casadi_sq( w33 );
  /* #165: @31 = (@31-@33) */
  w31 -= w33;
  /* #166: output[0][14] = @31 */
  if (res[0]) res[0][14] = w31;
  /* #167: @31 = input[3][45] */
  w31 = arg[3] ? arg[3][45] : 0;
  /* #168: @31 = (@0-@31) */
  w31  = (w00-w31);
  /* #169: @33 = sq(@31) */
  w33 = casadi_sq( w31 );
  /* #170: @34 = input[3][46] */
  w34 = arg[3] ? arg[3][46] : 0;
  /* #171: @34 = (@3-@34) */
  w34  = (w03-w34);
  /* #172: @35 = sq(@34) */
  w35 = casadi_sq( w34 );
  /* #173: @33 = (@33+@35) */
  w33 += w35;
  /* #174: @35 = input[3][47] */
  w35 = arg[3] ? arg[3][47] : 0;
  /* #175: @35 = sq(@35) */
  w35 = casadi_sq( w35 );
  /* #176: @33 = (@33-@35) */
  w33 -= w35;
  /* #177: output[0][15] = @33 */
  if (res[0]) res[0][15] = w33;
  /* #178: @33 = input[3][48] */
  w33 = arg[3] ? arg[3][48] : 0;
  /* #179: @33 = (@0-@33) */
  w33  = (w00-w33);
  /* #180: @35 = sq(@33) */
  w35 = casadi_sq( w33 );
  /* #181: @36 = input[3][49] */
  w36 = arg[3] ? arg[3][49] : 0;
  /* #182: @36 = (@3-@36) */
  w36  = (w03-w36);
  /* #183: @37 = sq(@36) */
  w37 = casadi_sq( w36 );
  /* #184: @35 = (@35+@37) */
  w35 += w37;
  /* #185: @37 = input[3][50] */
  w37 = arg[3] ? arg[3][50] : 0;
  /* #186: @37 = sq(@37) */
  w37 = casadi_sq( w37 );
  /* #187: @35 = (@35-@37) */
  w35 -= w37;
  /* #188: output[0][16] = @35 */
  if (res[0]) res[0][16] = w35;
  /* #189: @35 = input[3][51] */
  w35 = arg[3] ? arg[3][51] : 0;
  /* #190: @35 = (@0-@35) */
  w35  = (w00-w35);
  /* #191: @37 = sq(@35) */
  w37 = casadi_sq( w35 );
  /* #192: @38 = input[3][52] */
  w38 = arg[3] ? arg[3][52] : 0;
  /* #193: @38 = (@3-@38) */
  w38  = (w03-w38);
  /* #194: @39 = sq(@38) */
  w39 = casadi_sq( w38 );
  /* #195: @37 = (@37+@39) */
  w37 += w39;
  /* #196: @39 = input[3][53] */
  w39 = arg[3] ? arg[3][53] : 0;
  /* #197: @39 = sq(@39) */
  w39 = casadi_sq( w39 );
  /* #198: @37 = (@37-@39) */
  w37 -= w39;
  /* #199: output[0][17] = @37 */
  if (res[0]) res[0][17] = w37;
  /* #200: @37 = input[3][54] */
  w37 = arg[3] ? arg[3][54] : 0;
  /* #201: @37 = (@0-@37) */
  w37  = (w00-w37);
  /* #202: @39 = sq(@37) */
  w39 = casadi_sq( w37 );
  /* #203: @40 = input[3][55] */
  w40 = arg[3] ? arg[3][55] : 0;
  /* #204: @40 = (@3-@40) */
  w40  = (w03-w40);
  /* #205: @41 = sq(@40) */
  w41 = casadi_sq( w40 );
  /* #206: @39 = (@39+@41) */
  w39 += w41;
  /* #207: @41 = input[3][56] */
  w41 = arg[3] ? arg[3][56] : 0;
  /* #208: @41 = sq(@41) */
  w41 = casadi_sq( w41 );
  /* #209: @39 = (@39-@41) */
  w39 -= w41;
  /* #210: output[0][18] = @39 */
  if (res[0]) res[0][18] = w39;
  /* #211: @39 = input[3][57] */
  w39 = arg[3] ? arg[3][57] : 0;
  /* #212: @39 = (@0-@39) */
  w39  = (w00-w39);
  /* #213: @41 = sq(@39) */
  w41 = casadi_sq( w39 );
  /* #214: @42 = input[3][58] */
  w42 = arg[3] ? arg[3][58] : 0;
  /* #215: @42 = (@3-@42) */
  w42  = (w03-w42);
  /* #216: @43 = sq(@42) */
  w43 = casadi_sq( w42 );
  /* #217: @41 = (@41+@43) */
  w41 += w43;
  /* #218: @43 = input[3][59] */
  w43 = arg[3] ? arg[3][59] : 0;
  /* #219: @43 = sq(@43) */
  w43 = casadi_sq( w43 );
  /* #220: @41 = (@41-@43) */
  w41 -= w43;
  /* #221: output[0][19] = @41 */
  if (res[0]) res[0][19] = w41;
  /* #222: @41 = input[3][60] */
  w41 = arg[3] ? arg[3][60] : 0;
  /* #223: @41 = (@0-@41) */
  w41  = (w00-w41);
  /* #224: @43 = sq(@41) */
  w43 = casadi_sq( w41 );
  /* #225: @44 = input[3][61] */
  w44 = arg[3] ? arg[3][61] : 0;
  /* #226: @44 = (@3-@44) */
  w44  = (w03-w44);
  /* #227: @45 = sq(@44) */
  w45 = casadi_sq( w44 );
  /* #228: @43 = (@43+@45) */
  w43 += w45;
  /* #229: @45 = input[3][62] */
  w45 = arg[3] ? arg[3][62] : 0;
  /* #230: @45 = sq(@45) */
  w45 = casadi_sq( w45 );
  /* #231: @43 = (@43-@45) */
  w43 -= w45;
  /* #232: output[0][20] = @43 */
  if (res[0]) res[0][20] = w43;
  /* #233: @43 = input[3][63] */
  w43 = arg[3] ? arg[3][63] : 0;
  /* #234: @43 = (@0-@43) */
  w43  = (w00-w43);
  /* #235: @45 = sq(@43) */
  w45 = casadi_sq( w43 );
  /* #236: @46 = input[3][64] */
  w46 = arg[3] ? arg[3][64] : 0;
  /* #237: @46 = (@3-@46) */
  w46  = (w03-w46);
  /* #238: @47 = sq(@46) */
  w47 = casadi_sq( w46 );
  /* #239: @45 = (@45+@47) */
  w45 += w47;
  /* #240: @47 = input[3][65] */
  w47 = arg[3] ? arg[3][65] : 0;
  /* #241: @47 = sq(@47) */
  w47 = casadi_sq( w47 );
  /* #242: @45 = (@45-@47) */
  w45 -= w47;
  /* #243: output[0][21] = @45 */
  if (res[0]) res[0][21] = w45;
  /* #244: @45 = input[3][66] */
  w45 = arg[3] ? arg[3][66] : 0;
  /* #245: @45 = (@0-@45) */
  w45  = (w00-w45);
  /* #246: @47 = sq(@45) */
  w47 = casadi_sq( w45 );
  /* #247: @48 = input[3][67] */
  w48 = arg[3] ? arg[3][67] : 0;
  /* #248: @48 = (@3-@48) */
  w48  = (w03-w48);
  /* #249: @49 = sq(@48) */
  w49 = casadi_sq( w48 );
  /* #250: @47 = (@47+@49) */
  w47 += w49;
  /* #251: @49 = input[3][68] */
  w49 = arg[3] ? arg[3][68] : 0;
  /* #252: @49 = sq(@49) */
  w49 = casadi_sq( w49 );
  /* #253: @47 = (@47-@49) */
  w47 -= w49;
  /* #254: output[0][22] = @47 */
  if (res[0]) res[0][22] = w47;
  /* #255: @47 = input[3][69] */
  w47 = arg[3] ? arg[3][69] : 0;
  /* #256: @47 = (@0-@47) */
  w47  = (w00-w47);
  /* #257: @49 = sq(@47) */
  w49 = casadi_sq( w47 );
  /* #258: @50 = input[3][70] */
  w50 = arg[3] ? arg[3][70] : 0;
  /* #259: @50 = (@3-@50) */
  w50  = (w03-w50);
  /* #260: @51 = sq(@50) */
  w51 = casadi_sq( w50 );
  /* #261: @49 = (@49+@51) */
  w49 += w51;
  /* #262: @51 = input[3][71] */
  w51 = arg[3] ? arg[3][71] : 0;
  /* #263: @51 = sq(@51) */
  w51 = casadi_sq( w51 );
  /* #264: @49 = (@49-@51) */
  w49 -= w51;
  /* #265: output[0][23] = @49 */
  if (res[0]) res[0][23] = w49;
  /* #266: @49 = input[3][72] */
  w49 = arg[3] ? arg[3][72] : 0;
  /* #267: @49 = (@0-@49) */
  w49  = (w00-w49);
  /* #268: @51 = sq(@49) */
  w51 = casadi_sq( w49 );
  /* #269: @52 = input[3][73] */
  w52 = arg[3] ? arg[3][73] : 0;
  /* #270: @52 = (@3-@52) */
  w52  = (w03-w52);
  /* #271: @53 = sq(@52) */
  w53 = casadi_sq( w52 );
  /* #272: @51 = (@51+@53) */
  w51 += w53;
  /* #273: @53 = input[3][74] */
  w53 = arg[3] ? arg[3][74] : 0;
  /* #274: @53 = sq(@53) */
  w53 = casadi_sq( w53 );
  /* #275: @51 = (@51-@53) */
  w51 -= w53;
  /* #276: output[0][24] = @51 */
  if (res[0]) res[0][24] = w51;
  /* #277: @51 = input[3][75] */
  w51 = arg[3] ? arg[3][75] : 0;
  /* #278: @51 = (@0-@51) */
  w51  = (w00-w51);
  /* #279: @53 = sq(@51) */
  w53 = casadi_sq( w51 );
  /* #280: @54 = input[3][76] */
  w54 = arg[3] ? arg[3][76] : 0;
  /* #281: @54 = (@3-@54) */
  w54  = (w03-w54);
  /* #282: @55 = sq(@54) */
  w55 = casadi_sq( w54 );
  /* #283: @53 = (@53+@55) */
  w53 += w55;
  /* #284: @55 = input[3][77] */
  w55 = arg[3] ? arg[3][77] : 0;
  /* #285: @55 = sq(@55) */
  w55 = casadi_sq( w55 );
  /* #286: @53 = (@53-@55) */
  w53 -= w55;
  /* #287: output[0][25] = @53 */
  if (res[0]) res[0][25] = w53;
  /* #288: @53 = input[3][78] */
  w53 = arg[3] ? arg[3][78] : 0;
  /* #289: @53 = (@0-@53) */
  w53  = (w00-w53);
  /* #290: @55 = sq(@53) */
  w55 = casadi_sq( w53 );
  /* #291: @56 = input[3][79] */
  w56 = arg[3] ? arg[3][79] : 0;
  /* #292: @56 = (@3-@56) */
  w56  = (w03-w56);
  /* #293: @57 = sq(@56) */
  w57 = casadi_sq( w56 );
  /* #294: @55 = (@55+@57) */
  w55 += w57;
  /* #295: @57 = input[3][80] */
  w57 = arg[3] ? arg[3][80] : 0;
  /* #296: @57 = sq(@57) */
  w57 = casadi_sq( w57 );
  /* #297: @55 = (@55-@57) */
  w55 -= w57;
  /* #298: output[0][26] = @55 */
  if (res[0]) res[0][26] = w55;
  /* #299: @55 = input[3][81] */
  w55 = arg[3] ? arg[3][81] : 0;
  /* #300: @55 = (@0-@55) */
  w55  = (w00-w55);
  /* #301: @57 = sq(@55) */
  w57 = casadi_sq( w55 );
  /* #302: @58 = input[3][82] */
  w58 = arg[3] ? arg[3][82] : 0;
  /* #303: @58 = (@3-@58) */
  w58  = (w03-w58);
  /* #304: @59 = sq(@58) */
  w59 = casadi_sq( w58 );
  /* #305: @57 = (@57+@59) */
  w57 += w59;
  /* #306: @59 = input[3][83] */
  w59 = arg[3] ? arg[3][83] : 0;
  /* #307: @59 = sq(@59) */
  w59 = casadi_sq( w59 );
  /* #308: @57 = (@57-@59) */
  w57 -= w59;
  /* #309: output[0][27] = @57 */
  if (res[0]) res[0][27] = w57;
  /* #310: @57 = input[3][84] */
  w57 = arg[3] ? arg[3][84] : 0;
  /* #311: @57 = (@0-@57) */
  w57  = (w00-w57);
  /* #312: @59 = sq(@57) */
  w59 = casadi_sq( w57 );
  /* #313: @60 = input[3][85] */
  w60 = arg[3] ? arg[3][85] : 0;
  /* #314: @60 = (@3-@60) */
  w60  = (w03-w60);
  /* #315: @61 = sq(@60) */
  w61 = casadi_sq( w60 );
  /* #316: @59 = (@59+@61) */
  w59 += w61;
  /* #317: @61 = input[3][86] */
  w61 = arg[3] ? arg[3][86] : 0;
  /* #318: @61 = sq(@61) */
  w61 = casadi_sq( w61 );
  /* #319: @59 = (@59-@61) */
  w59 -= w61;
  /* #320: output[0][28] = @59 */
  if (res[0]) res[0][28] = w59;
  /* #321: @59 = input[3][87] */
  w59 = arg[3] ? arg[3][87] : 0;
  /* #322: @0 = (@0-@59) */
  w00 -= w59;
  /* #323: @59 = sq(@0) */
  w59 = casadi_sq( w00 );
  /* #324: @61 = input[3][88] */
  w61 = arg[3] ? arg[3][88] : 0;
  /* #325: @3 = (@3-@61) */
  w03 -= w61;
  /* #326: @61 = sq(@3) */
  w61 = casadi_sq( w03 );
  /* #327: @59 = (@59+@61) */
  w59 += w61;
  /* #328: @61 = input[3][89] */
  w61 = arg[3] ? arg[3][89] : 0;
  /* #329: @61 = sq(@61) */
  w61 = casadi_sq( w61 );
  /* #330: @59 = (@59-@61) */
  w59 -= w61;
  /* #331: output[0][29] = @59 */
  if (res[0]) res[0][29] = w59;
  /* #332: @62 = zeros(5x30,60nz) */
  casadi_clear(w62, 60);
  /* #333: @1 = (2.*@1) */
  w01 = (2.* w01 );
  /* #334: @63 = ones(5x1,4nz) */
  casadi_fill(w63, 4, 1.);
  /* #335: {@59, NULL, NULL, NULL, NULL} = vertsplit(@63) */
  w59 = w63[0];
  /* #336: @1 = (@1*@59) */
  w01 *= w59;
  /* #337: @2 = (2.*@2) */
  w02 = (2.* w02 );
  /* #338: @2 = (@2*@59) */
  w02 *= w59;
  /* #339: @5 = (2.*@5) */
  w05 = (2.* w05 );
  /* #340: @5 = (@5*@59) */
  w05 *= w59;
  /* #341: @7 = (2.*@7) */
  w07 = (2.* w07 );
  /* #342: @7 = (@7*@59) */
  w07 *= w59;
  /* #343: @9 = (2.*@9) */
  w09 = (2.* w09 );
  /* #344: @9 = (@9*@59) */
  w09 *= w59;
  /* #345: @11 = (2.*@11) */
  w11 = (2.* w11 );
  /* #346: @11 = (@11*@59) */
  w11 *= w59;
  /* #347: @13 = (2.*@13) */
  w13 = (2.* w13 );
  /* #348: @13 = (@13*@59) */
  w13 *= w59;
  /* #349: @15 = (2.*@15) */
  w15 = (2.* w15 );
  /* #350: @15 = (@15*@59) */
  w15 *= w59;
  /* #351: @17 = (2.*@17) */
  w17 = (2.* w17 );
  /* #352: @17 = (@17*@59) */
  w17 *= w59;
  /* #353: @19 = (2.*@19) */
  w19 = (2.* w19 );
  /* #354: @19 = (@19*@59) */
  w19 *= w59;
  /* #355: @21 = (2.*@21) */
  w21 = (2.* w21 );
  /* #356: @21 = (@21*@59) */
  w21 *= w59;
  /* #357: @23 = (2.*@23) */
  w23 = (2.* w23 );
  /* #358: @23 = (@23*@59) */
  w23 *= w59;
  /* #359: @25 = (2.*@25) */
  w25 = (2.* w25 );
  /* #360: @25 = (@25*@59) */
  w25 *= w59;
  /* #361: @27 = (2.*@27) */
  w27 = (2.* w27 );
  /* #362: @27 = (@27*@59) */
  w27 *= w59;
  /* #363: @29 = (2.*@29) */
  w29 = (2.* w29 );
  /* #364: @29 = (@29*@59) */
  w29 *= w59;
  /* #365: @31 = (2.*@31) */
  w31 = (2.* w31 );
  /* #366: @31 = (@31*@59) */
  w31 *= w59;
  /* #367: @33 = (2.*@33) */
  w33 = (2.* w33 );
  /* #368: @33 = (@33*@59) */
  w33 *= w59;
  /* #369: @35 = (2.*@35) */
  w35 = (2.* w35 );
  /* #370: @35 = (@35*@59) */
  w35 *= w59;
  /* #371: @37 = (2.*@37) */
  w37 = (2.* w37 );
  /* #372: @37 = (@37*@59) */
  w37 *= w59;
  /* #373: @39 = (2.*@39) */
  w39 = (2.* w39 );
  /* #374: @39 = (@39*@59) */
  w39 *= w59;
  /* #375: @41 = (2.*@41) */
  w41 = (2.* w41 );
  /* #376: @41 = (@41*@59) */
  w41 *= w59;
  /* #377: @43 = (2.*@43) */
  w43 = (2.* w43 );
  /* #378: @43 = (@43*@59) */
  w43 *= w59;
  /* #379: @45 = (2.*@45) */
  w45 = (2.* w45 );
  /* #380: @45 = (@45*@59) */
  w45 *= w59;
  /* #381: @47 = (2.*@47) */
  w47 = (2.* w47 );
  /* #382: @47 = (@47*@59) */
  w47 *= w59;
  /* #383: @49 = (2.*@49) */
  w49 = (2.* w49 );
  /* #384: @49 = (@49*@59) */
  w49 *= w59;
  /* #385: @51 = (2.*@51) */
  w51 = (2.* w51 );
  /* #386: @51 = (@51*@59) */
  w51 *= w59;
  /* #387: @53 = (2.*@53) */
  w53 = (2.* w53 );
  /* #388: @53 = (@53*@59) */
  w53 *= w59;
  /* #389: @55 = (2.*@55) */
  w55 = (2.* w55 );
  /* #390: @55 = (@55*@59) */
  w55 *= w59;
  /* #391: @57 = (2.*@57) */
  w57 = (2.* w57 );
  /* #392: @57 = (@57*@59) */
  w57 *= w59;
  /* #393: @0 = (2.*@0) */
  w00 = (2.* w00 );
  /* #394: @0 = (@0*@59) */
  w00 *= w59;
  /* #395: @64 = vertcat(@1, @2, @5, @7, @9, @11, @13, @15, @17, @19, @21, @23, @25, @27, @29, @31, @33, @35, @37, @39, @41, @43, @45, @47, @49, @51, @53, @55, @57, @0) */
  rr=w64;
  *rr++ = w01;
  *rr++ = w02;
  *rr++ = w05;
  *rr++ = w07;
  *rr++ = w09;
  *rr++ = w11;
  *rr++ = w13;
  *rr++ = w15;
  *rr++ = w17;
  *rr++ = w19;
  *rr++ = w21;
  *rr++ = w23;
  *rr++ = w25;
  *rr++ = w27;
  *rr++ = w29;
  *rr++ = w31;
  *rr++ = w33;
  *rr++ = w35;
  *rr++ = w37;
  *rr++ = w39;
  *rr++ = w41;
  *rr++ = w43;
  *rr++ = w45;
  *rr++ = w47;
  *rr++ = w49;
  *rr++ = w51;
  *rr++ = w53;
  *rr++ = w55;
  *rr++ = w57;
  *rr++ = w00;
  /* #396: (@62[:60:2] = @64) */
  for (rr=w62+0, cs=w64; rr!=w62+60; rr+=2) *rr = *cs++;
  /* #397: @4 = (2.*@4) */
  w04 = (2.* w04 );
  /* #398: @1 = ones(5x1,1nz) */
  w01 = 1.;
  /* #399: {NULL, @2, NULL, NULL, NULL} = vertsplit(@1) */
  w02 = w01;
  /* #400: @4 = (@4*@2) */
  w04 *= w02;
  /* #401: @6 = (2.*@6) */
  w06 = (2.* w06 );
  /* #402: @6 = (@6*@2) */
  w06 *= w02;
  /* #403: @8 = (2.*@8) */
  w08 = (2.* w08 );
  /* #404: @8 = (@8*@2) */
  w08 *= w02;
  /* #405: @10 = (2.*@10) */
  w10 = (2.* w10 );
  /* #406: @10 = (@10*@2) */
  w10 *= w02;
  /* #407: @12 = (2.*@12) */
  w12 = (2.* w12 );
  /* #408: @12 = (@12*@2) */
  w12 *= w02;
  /* #409: @14 = (2.*@14) */
  w14 = (2.* w14 );
  /* #410: @14 = (@14*@2) */
  w14 *= w02;
  /* #411: @16 = (2.*@16) */
  w16 = (2.* w16 );
  /* #412: @16 = (@16*@2) */
  w16 *= w02;
  /* #413: @18 = (2.*@18) */
  w18 = (2.* w18 );
  /* #414: @18 = (@18*@2) */
  w18 *= w02;
  /* #415: @20 = (2.*@20) */
  w20 = (2.* w20 );
  /* #416: @20 = (@20*@2) */
  w20 *= w02;
  /* #417: @22 = (2.*@22) */
  w22 = (2.* w22 );
  /* #418: @22 = (@22*@2) */
  w22 *= w02;
  /* #419: @24 = (2.*@24) */
  w24 = (2.* w24 );
  /* #420: @24 = (@24*@2) */
  w24 *= w02;
  /* #421: @26 = (2.*@26) */
  w26 = (2.* w26 );
  /* #422: @26 = (@26*@2) */
  w26 *= w02;
  /* #423: @28 = (2.*@28) */
  w28 = (2.* w28 );
  /* #424: @28 = (@28*@2) */
  w28 *= w02;
  /* #425: @30 = (2.*@30) */
  w30 = (2.* w30 );
  /* #426: @30 = (@30*@2) */
  w30 *= w02;
  /* #427: @32 = (2.*@32) */
  w32 = (2.* w32 );
  /* #428: @32 = (@32*@2) */
  w32 *= w02;
  /* #429: @34 = (2.*@34) */
  w34 = (2.* w34 );
  /* #430: @34 = (@34*@2) */
  w34 *= w02;
  /* #431: @36 = (2.*@36) */
  w36 = (2.* w36 );
  /* #432: @36 = (@36*@2) */
  w36 *= w02;
  /* #433: @38 = (2.*@38) */
  w38 = (2.* w38 );
  /* #434: @38 = (@38*@2) */
  w38 *= w02;
  /* #435: @40 = (2.*@40) */
  w40 = (2.* w40 );
  /* #436: @40 = (@40*@2) */
  w40 *= w02;
  /* #437: @42 = (2.*@42) */
  w42 = (2.* w42 );
  /* #438: @42 = (@42*@2) */
  w42 *= w02;
  /* #439: @44 = (2.*@44) */
  w44 = (2.* w44 );
  /* #440: @44 = (@44*@2) */
  w44 *= w02;
  /* #441: @46 = (2.*@46) */
  w46 = (2.* w46 );
  /* #442: @46 = (@46*@2) */
  w46 *= w02;
  /* #443: @48 = (2.*@48) */
  w48 = (2.* w48 );
  /* #444: @48 = (@48*@2) */
  w48 *= w02;
  /* #445: @50 = (2.*@50) */
  w50 = (2.* w50 );
  /* #446: @50 = (@50*@2) */
  w50 *= w02;
  /* #447: @52 = (2.*@52) */
  w52 = (2.* w52 );
  /* #448: @52 = (@52*@2) */
  w52 *= w02;
  /* #449: @54 = (2.*@54) */
  w54 = (2.* w54 );
  /* #450: @54 = (@54*@2) */
  w54 *= w02;
  /* #451: @56 = (2.*@56) */
  w56 = (2.* w56 );
  /* #452: @56 = (@56*@2) */
  w56 *= w02;
  /* #453: @58 = (2.*@58) */
  w58 = (2.* w58 );
  /* #454: @58 = (@58*@2) */
  w58 *= w02;
  /* #455: @60 = (2.*@60) */
  w60 = (2.* w60 );
  /* #456: @60 = (@60*@2) */
  w60 *= w02;
  /* #457: @3 = (2.*@3) */
  w03 = (2.* w03 );
  /* #458: @3 = (@3*@2) */
  w03 *= w02;
  /* #459: @64 = vertcat(@4, @6, @8, @10, @12, @14, @16, @18, @20, @22, @24, @26, @28, @30, @32, @34, @36, @38, @40, @42, @44, @46, @48, @50, @52, @54, @56, @58, @60, @3) */
  rr=w64;
  *rr++ = w04;
  *rr++ = w06;
  *rr++ = w08;
  *rr++ = w10;
  *rr++ = w12;
  *rr++ = w14;
  *rr++ = w16;
  *rr++ = w18;
  *rr++ = w20;
  *rr++ = w22;
  *rr++ = w24;
  *rr++ = w26;
  *rr++ = w28;
  *rr++ = w30;
  *rr++ = w32;
  *rr++ = w34;
  *rr++ = w36;
  *rr++ = w38;
  *rr++ = w40;
  *rr++ = w42;
  *rr++ = w44;
  *rr++ = w46;
  *rr++ = w48;
  *rr++ = w50;
  *rr++ = w52;
  *rr++ = w54;
  *rr++ = w56;
  *rr++ = w58;
  *rr++ = w60;
  *rr++ = w03;
  /* #460: (@62[1:61:2] = @64) */
  for (rr=w62+1, cs=w64; rr!=w62+61; rr+=2) *rr = *cs++;
  /* #461: output[1][0] = @62 */
  casadi_copy(w62, 60, res[1]);
  return 0;
}

CASADI_SYMBOL_EXPORT int diffusion_projection_unicycle_constr_h_e_fun_jac_uxt_zt(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int diffusion_projection_unicycle_constr_h_e_fun_jac_uxt_zt_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int diffusion_projection_unicycle_constr_h_e_fun_jac_uxt_zt_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void diffusion_projection_unicycle_constr_h_e_fun_jac_uxt_zt_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int diffusion_projection_unicycle_constr_h_e_fun_jac_uxt_zt_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void diffusion_projection_unicycle_constr_h_e_fun_jac_uxt_zt_release(int mem) {
}

CASADI_SYMBOL_EXPORT void diffusion_projection_unicycle_constr_h_e_fun_jac_uxt_zt_incref(void) {
}

CASADI_SYMBOL_EXPORT void diffusion_projection_unicycle_constr_h_e_fun_jac_uxt_zt_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int diffusion_projection_unicycle_constr_h_e_fun_jac_uxt_zt_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int diffusion_projection_unicycle_constr_h_e_fun_jac_uxt_zt_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real diffusion_projection_unicycle_constr_h_e_fun_jac_uxt_zt_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* diffusion_projection_unicycle_constr_h_e_fun_jac_uxt_zt_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* diffusion_projection_unicycle_constr_h_e_fun_jac_uxt_zt_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* diffusion_projection_unicycle_constr_h_e_fun_jac_uxt_zt_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* diffusion_projection_unicycle_constr_h_e_fun_jac_uxt_zt_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    case 1: return casadi_s4;
    case 2: return casadi_s5;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int diffusion_projection_unicycle_constr_h_e_fun_jac_uxt_zt_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 34;
  if (sz_res) *sz_res = 8;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 156;
  return 0;
}

CASADI_SYMBOL_EXPORT int diffusion_projection_unicycle_constr_h_e_fun_jac_uxt_zt_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 34*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 8*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 156*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
