hunav_loader:
  ros__parameters:
    yaml_base_name: office_2_agents
    simulator: Gazebo Fortress
    map: office
    publish_people: true
    global_goals:
      1:
        x: -3.000
        y: 1.500
      2:
        x: 3.000
        y: 1.500
      3:
        x: 3.000
        y: -1.500
      4:
        x: -3.000
        y: -1.500
    agents:
      - agent1
      - agent2
    agent1:
      id: 1
      group_id: -1
      skin: 4
      max_vel: 0.0
      radius: 0.4
      goal_radius: 0.35
      cyclic_goals: true
      init_pose:
        x: 1.500
        y: 0.500
        z: 1.250
        h: 0.000
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 0.0
        obstacle_force_factor: 0.0
        social_force_factor: 0.0
        other_force_factor: 0.0
      goals:
        - 2
        - 1
    agent2:
      id: 2
      group_id: -1
      skin: 3
      max_vel: 0.0
      radius: 0.4
      goal_radius: 0.35
      cyclic_goals: true
      init_pose:
        x: 1.500
        y: -0.500
        z: 1.250
        h: 3.142
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 0.0
        obstacle_force_factor: 0.0
        social_force_factor: 0.0
        other_force_factor: 0.0
      goals:
        - 4
        - 3
