policy_cmd_vel_node:
  ros__parameters:
    people_topic: /people
    ignore_people_for_policy: true
    odom_topic: /jackal1/platform/odom/filtered
    map_topic: /map
    goal_topic: /goal_pose
    robot_goal_topic: /jackal1/goal_pose
    cmd_vel_topic: /debug_cmd_vel
    active_goal_marker_topic: /social_nav_diffusion/active_goal_marker
    goal_path_topic: /social_nav_diffusion/goal_path
    policy_debug_topic: /social_nav_diffusion/policy_debug
    cmd_frame_id: base_link
    target_policy_frame: map
    people_frame: map

nav2_goal_to_pose_bridge:
  ros__parameters:
    robot_odom_topic: /jackal1/platform/odom/filtered
    goal_topic: /goal_pose
    robot_goal_topic: /jackal1/goal_pose
    active_goal_marker_topic: /social_nav_diffusion/active_goal_marker
    navigate_to_pose_action: /navigate_to_pose
    robot_navigate_to_pose_action: /jackal1/navigate_to_pose

jackal1_topic_checklist:
  ros__parameters:
    lidar_topic: /jackal1/sensors/lidar3d_0/scan
    odom_topic: /jackal1/platform/odom/filtered
    imu_topic: /jackal1/sensors/imu_0/data
    real_cmd_vel_topic: /jackal1/cmd_vel
    tf_base_frame: base_link
    tf_odom_frame: odom
    tf_map_frame: map
