policy_cmd_vel_node:
  ros__parameters:
    people_topic: /people
    odom_topic: /cpr_j100_0001/platform/odom/filtered
    map_topic: /cpr_j100_0001/map
    goal_topic: /goal_pose
    robot_goal_topic: /cpr_j100_0001/goal_pose
    cmd_vel_topic: /cpr_j100_0001/cmd_vel
    active_goal_marker_topic: /social_nav_diffusion/active_goal_marker
    policy_debug_topic: /social_nav_diffusion/policy_debug
    cmd_frame_id: base_link
    target_policy_frame: map
    people_frame: map

nav2_goal_to_pose_bridge:
  ros__parameters:
    robot_odom_topic: /cpr_j100_0001/platform/odom
    goal_topic: /goal_pose
    robot_goal_topic: /cpr_j100_0001/goal_pose
    active_goal_marker_topic: /social_nav_diffusion/active_goal_marker
    navigate_to_pose_action: /navigate_to_pose
    robot_navigate_to_pose_action: /cpr_j100_0001/navigate_to_pose
